server {
    listen 9092;
    # Убираем фиксированный server_name, чтобы Nginx принимал запросы на любой IP
    # server_name 203.0.113.20;

    root /video-enhancer/animeWEB/public;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}